const words =  [
    {
        name:"يبتسم",
        url:"kjsd"
    },
    {
        name:"ابتسام",
        url:""
    },
    {
        name:"بسم الله"
    }

];

const all = {
  0: "math/0.JPG",
  1: "math/1.JPG",
  2: "math/2.JPG",
  3: "math/3.JPG",
  4: "math/4.JPG",
  5: "math/5.JPG",
  6: "math/6.JPG",
  7: "math/7.JPG",
  8: "math/8.JPG",
  9: "math/9.JPG",
  10: "math/10.JPG",
  11: "math/11.JPG",
  13: "math/13.JPG",
  14: "math/14.JPG",
  15: "math/15.JPG",
  17: "math/17.JPG",
  20: "math/20.JPG",
  21: "math/21.JPG",
  22: "math/22.JPG",
  30: "math/30.JPG",
  32: "math/32.JPG",
  40: "math/40.JPG",
  50: "math/50.JPG",
  60: "math/60.JPG",
  70: "math/70.JPG",
  80: "math/80.JPG",
  90: "math/90.JPG",
  100: "math/100.JPG",
  200: "math/200.JPG",
  300: "math/300.JPG",
  1000: "math/1000.JPG",
  2000: "math/2000.JPG",
  A: "english/A.png",
  B: "english/B.png",
  C: "english/C.png",
  D: "english/D.png",
  E: "english/E.png",
  F: "english/F.png",
  G: "english/G.png",
  H: "english/H.png",
  I: "english/I.png",
  J: "english/J.png",
  K: "english/K.png",
  L: "english/L.png",
  M: "english/M.png",
  N: "english/N.png",
  O: "english/O.png",
  P: "english/P.png",
  Q: "english/Q.png",
  R: "english/R.png",
  S: "english/S.png",
  T: "english/T.png",
  U: "english/U.png",
  V: "english/V.png",
  W: "english/W.png",
  X: "english/X.png",
  Y: "english/Y.png",
  Z: "english/Z.png",
  "اخر مرة": "months/اخر مرة.png",
  "اشهر ميلادية": "months/اشهر ميلادية.png",
  "اشهر هجرية": "months/اشهر هجرية.jpg",
  الاثنين: "months/الاثنين.png",
  الاحد: "months/الاحد.png",
  الاربعاء: "months/الاربعاء.png",
  الان: "months/الان.png",
  الثلاثاء: "months/الثلاثاء.png",
  الجمعة: "months/الجمعة.png",
  الخميس: "months/الخميس.png",
  السبت: "months/السبت.png",
  امس: "months/امس.png",
  "اول مرة": "months/اول مرة.png",
  ايار: "months/ايار.jpg",
  "ايام الاسبوع": "months/ايام الاسبوع.png",
  "تشرين الثاني": "months/تشرين الثاني.jpg",
  تقويم: "months/تقويم.png",
  ثانية: "months/ثانية.png",
  دائما: "months/دائما.png",
  دقيقة: "months/دقيقة.jpg",
  "ذي الحجة": "months/ذي الحجة.jpg",
  "ذي القعدة": "months/ذي القعدة.jpg",
  "ربع ساعة": "months/ربع ساعة.png",
  "ساعة وحدة الا ربع": "months/ساعة وحدة الا ربع.jpg",
  "ساعة وحدة وخمسة": "months/ساعة وحدة وخمسة.jpg",
  ساعة: "months/ساعة.png",
  "سنة ميلادية": "months/سنة ميلادية.jpg",
  "سنة هجرية": "months/سنة هجرية.png",
  شباط: "months/شباط.jpg",
  شعبان: "months/شعبان.jpg",
  "شهر الاو": "months/شهر الاو.png",
  "شهر التاسع": "months/شهر التاسع.png",
  "شهر الثالث": "months/شهر الثالث.png",
  "شهر الثامن": "months/شهر الثامن.jpg",
  "شهر الرابع": "months/شهر الرابع.png",
  "شهر السابع": "months/شهر السابع.png",
  "شهر السادس": "months/شهر السادس.png",
  "شهر العاشر": "months/شهر العاشر.png",
  "شهر جمادي الاول": "months/شهر جمادي الاول.png",
  "شهر جمادي الثاني": "months/شهر جمادي الثاني.png",
  "شهر ربيع الاول": "months/شهر ربيع الاول.png",
  "شهر ربيع الثاني": "months/شهر ربيع الثاني.png",
  "شهر رجب": "months/شهر رجب.png",
  "شهر رمضان": "months/شهر رمضان.png",
  "شهر شوال": "months/شهر شوال.png",
  "شهر صفر": "months/شهر صفر.png",
  ظهر: "verbs/ظهر.JPG",
  عشاء: "months/عشاء.png",
  عصر: "months/عصر.png",
  غدا: "months/غدا.png",
  غداء: "months/غداء.png",
  فترة: "months/فترة.png",
  فجر: "months/فجر.png",
  فطور: "months/فطور.jpg",
  "كانون الاول": "months/كانون الاول.jpg",
  ليل: "months/ليل.png",
  ماضي: "months/ماضي.png",
  محرم: "months/محرم.jpg",
  مرتين: "months/مرتين.jpg",
  مستقبل: "months/مستقبل.png",
  مغرب: "months/مغرب.jpg",
  "نصف ساعة": "months/نصف ساعة.png",
  نهار: "months/نهار.png",
  "وقت مبكر": "months/وقت مبكر.png",
  "وقت متاخر": "months/وقت متاخر.png",
  وقت: "months/وقت.png",
  يوم: "months/يوم.png",
  Capture: "verbs/Capture.JPG",
  ابتسم: "verbs/ابتسم.JPG",
  ابتعد: "verbs/ابتعد.JPG",
  اتقن: "verbs/اتقن.JPG",
  اجاب: "verbs/اجاب.JPG",
  اجتهد: "verbs/اجتهد.JPG",
  احب: "verbs/احب.JPG",
  احترم: "verbs/احترم.JPG",
  اختار: "math/اختار.JPG",
  اختفى: "verbs/اختفى.JPG",
  اخذ: "verbs/اخذ.JPG",
  اخفى: "verbs/اخفى.JPG",
  اراد: "verbs/اراد.JPG",
  ارتفع: "verbs/ارتفع.JPG",
  استاذن: "verbs/استاذن.JPG",
  استثمر: "verbs/استثمر.JPG",
  استحدث: "verbs/استحدث.JPG",
  استحم: "verbs/استحم.JPG",
  استطاع: "verbs/استطاع.JPG",
  استعان: "verbs/استعان.JPG",
  استعمل: "verbs/استعمل.JPG",
  استغل: "verbs/استغل.JPG",
  استفاد: "verbs/استفاد.JPG",
  استفز: "verbs/استفز.JPG",
  استمر: "verbs/استمر.JPG",
  استيقظ: "verbs/استيقظ.JPG",
  اشتاق: "verbs/اشتاق.JPG",
  اشتاق1: "verbs/اشتاق1.JPG",
  اشترى: "verbs/اشترى.JPG",
  اشتهر: "verbs/اشتهر.JPG",
  اشرف: "verbs/اشرف.JPG",
  اطفى: "verbs/اطفى.JPG",
  اعتدى: "verbs/اعتدى.JPG",
  اعتذر: "verbs/اعتذر.JPG",
  اعتنى: "verbs/اعتنى.JPG",
  اعطى: "verbs/اعطى.JPG",
  اكتشف: "verbs/اكتشف.JPG",
  اكد: "verbs/اكد.JPG",
  اكل: "verbs/اكل.JPG",
  التقى: "verbs/التقى.JPG",
  امر: "verbs/امر.JPG",
  انتبه: "verbs/انتبه.JPG",
  انتهى: "verbs/انتهى.JPG",
  اندهش: "verbs/اندهش.JPG",
  انشد: "verbs/انشد.JPG",
  انضم: "verbs/انضم.JPG",
  باع: "verbs/باع.JPG",
  بنى: "verbs/بنى.JPG",
  تاب: "verbs/تاب.JPG",
  تاخر: "verbs/تاخر.JPG",
  تالم: "verbs/تالم.JPG",
  تاه: "verbs/تاه.JPG",
  تجاهل: "verbs/تجاهل.JPG",
  تحدى: "verbs/تحدى.JPG",
  تذكر: "verbs/تذكر.JPG",
  ترك: "verbs/ترك.JPG",
  تزحلق: "verbs/تزحلق.JPG",
  تسابق: "verbs/تسابق.JPG",
  تسلق: "verbs/تسلق.JPG",
  تشقق: "verbs/تشقق.JPG",
  تعلم: "verbs/تعلم.JPG",
  تفقد: "verbs/تفقد.JPG",
  تقدم: "verbs/تقدم.JPG",
  تكاثر: "verbs/تكاثر.JPG",
  تلف: "verbs/تلف.JPG",
  تمنى: "verbs/تمنى.JPG",
  تميز: "verbs/تميز.JPG",
  تناوب: "verbs/تناوب.JPG",
  توسع: "verbs/توسع.JPG",
  توقف: "verbs/توقف.JPG",
  جذف: "verbs/جذف.JPG",
  جلب: "verbs/جلب.JPG",
  حافظ: "verbs/حافظ.JPG",
  حاول: "verbs/حاول.JPG",
  حث: "verbs/حث.JPG",
  حجب: "verbs/حجب.JPG",
  حرث: "verbs/حرث.JPG",
  حرر: "verbs/حرر.JPG",
  حزر: "verbs/حزر.JPG",
  حصد: "verbs/حصد.JPG",
  حكم: "verbs/حكم.JPG",
  حلق: "verbs/حلق.JPG",
  حمل: "verbs/حمل.JPG",
  خرج: "verbs/خرج.JPG",
  خسر: "verbs/خسر.JPG",
  خطط: "verbs/خطط.JPG",
  دافع: "verbs/دافع.JPG",
  دحر: "verbs/دحر.JPG",
  دحر1: "verbs/دحر1.JPG",
  درب: "verbs/درب.JPG",
  دعم: "verbs/دعم.JPG",
  دفع: "verbs/دفع.JPG",
  دفن: "verbs/دفن.JPG",
  ذهب: "science/ذهب.png",
  رأى: "verbs/رأى.JPG",
  راقب: "verbs/راقب.JPG",
  ربح: "verbs/ربح.JPG",
  ربط: "verbs/ربط.JPG",
  ربى: "verbs/ربى.JPG",
  رتب: "verbs/رتب.JPG",
  رسم: "arts/رسم.png",
  رفض: "verbs/رفض.JPG",
  ركب: "verbs/ركب.JPG",
  ركض: "verbs/ركض.JPG",
  زار: "verbs/زار.JPG",
  زرع: "science/زرع.png",
  ساعد: "verbs/ساعد.JPG",
  سال: "verbs/سال.JPG",
  سامح: "verbs/سامح.JPG",
  سبح1: "verbs/سبح1.JPG",
  سبح2: "verbs/سبح2.JPG",
  سحب: "verbs/سحب.JPG",
  "سخر من": "verbs/سخر من.JPG",
  سرق: "verbs/سرق.JPG",
  سقط: "verbs/سقط.JPG",
  سقى: "verbs/سقى.JPG",
  سمع: "verbs/سمع.JPG",
  سهر: "verbs/سهر.JPG",
  سهر1: "verbs/سهر1.JPG",
  شارك: "verbs/شارك.JPG",
  شرب: "verbs/شرب.JPG",
  شكر: "verbs/شكر.JPG",
  شم1: "verbs/شم1.JPG",
  شم2: "verbs/شم2.JPG",
  صاحب: "verbs/صاحب.JPG",
  صاد: "verbs/صاد.JPG",
  صعد: "verbs/صعد.JPG",
  صنع: "verbs/صنع.JPG",
  ضحك: "verbs/ضحك.JPG",
  ضرب: "verbs/ضرب.JPG",
  طلع: "verbs/طلع.JPG",
  عاد: "verbs/عاد.JPG",
  عاش1: "verbs/عاش1.JPG",
  عاش2: "verbs/عاش2.JPG",
  عالج: "verbs/عالج.JPG",
  عبر: "verbs/عبر.JPG",
  عرف: "verbs/عرف.JPG",
  عزف: "verbs/عزف.JPG",
  عزل: "verbs/عزل.JPG",
  عمل: "verbs/عمل.JPG",
  غرد: "verbs/غرد.JPG",
  غسل: "verbs/غسل.JPG",
  غفر: "verbs/غفر.JPG",
  غفر1: "verbs/غفر1.JPG",
  فاز: "verbs/فاز.JPG",
  فتح: "verbs/فتح.JPG",
  فتش: "verbs/فتش.JPG",
  فشل: "verbs/فشل.JPG",
  "فشى سر 1": "verbs/فشى سر 1.JPG",
  "فشى سر": "verbs/فشى سر.JPG",
  فصل: "verbs/فصل.JPG",
  فكر: "verbs/فكر.JPG",
  قاد: "verbs/قاد.JPG",
  قال: "verbs/قال.JPG",
  قام: "verbs/قام.JPG",
  قدم: "verbs/قدم.JPG",
  قرا: "verbs/قرا.JPG",
  قفز: "verbs/قفز.JPG",
  كتب: "verbs/كتب.JPG",
  كرم: "verbs/كرم.JPG",
  كره: "verbs/كره.JPG",
  كسر: "math/كسر.JPG",
  لجا: "verbs/لجا.JPG",
  لعب: "verbs/لعب.JPG",
  لوح: "verbs/لوح.JPG",
  مسك: "verbs/مسك.JPG",
  مشى: "verbs/مشى.JPG",
  نادى: "verbs/نادى.JPG",
  نام: "verbs/نام.JPG",
  نثر: "verbs/نثر.JPG",
  ندم: "verbs/ندم.JPG",
  نزل: "verbs/نزل.JPG",
  نسى: "verbs/نسى.JPG",
  نصح1: "verbs/نصح1.JPG",
  نصح2: "verbs/نصح2.JPG",
  نضج1: "verbs/نضج1.JPG",
  نضج2: "verbs/نضج2.JPG",
  نظر: "verbs/نظر.JPG",
  نقل: "verbs/نقل.JPG",
  هبط: "verbs/هبط.JPG",
  هدم: "verbs/هدم.JPG",
  هدم1: "verbs/هدم1.JPG",
  هرب: "verbs/هرب.JPG",
  همل: "verbs/همل.JPG",
  "هيا حضر": "verbs/هيا حضر.JPG",
  وجد: "verbs/وجد.JPG",
  ودع: "verbs/ودع.JPG",
  وزع: "verbs/وزع.JPG",
  وضع: "verbs/وضع.JPG",
  وفر: "verbs/وفر.JPG",
  وقف: "verbs/وقف.JPG",
  ابرة: "house/ابرة.jpg",
  اثاث: "house/اثاث.jpg",
  بئر: "house/بئر.png",
  باب: "house/باب.png",
  بطانية: "house/بطانية.png",
  بنطلون: "house/بنطلون.png",
  بيت: "house/بيت.png",
  تلفزيون: "house/تلفزيون.png",
  تلفون: "house/تلفون.png",
  ثلاجة: "house/ثلاجة.png",
  "جرس كهربائي": "house/جرس كهربائي.png",
  جرس: "house/جرس.png",
  جواريب: "house/جواريب.jpg",
  حائط: "house/حائط.png",
  حمام: "house/حمام.jpg",
  خزان: "house/خزان.png",
  خلاط: "house/خلاط.png",
  خيط: "house/خيط.png",
  درج: "house/درج.png",
  "دلة القهوة": "house/دلة القهوة.png",
  راديو: "house/راديو.png",
  رباط: "house/رباط.png",
  ستائر: "house/ستائر.png",
  ستلايت: "house/ستلايت.png",
  سجاد: "house/سجاد.png",
  "سخان الماء": "house/سخان الماء.jpg",
  سرير: "house/سرير.png",
  سقف: "house/سقف.png",
  سكين: "house/سكين.png",
  "سلة مهملات": "house/سلة مهملات.png",
  سمنت: "house/سمنت.png",
  سوق: "house/سوق.jpg",
  شباك: "house/شباك.png",
  شخاط: "house/شخاط.png",
  شرشف: "house/شرشف.png",
  شوكة: "house/شوكة.png",
  صابون: "house/صابون.png",
  صحن: "house/صحن.jpg",
  صندوق: "house/صندوق.jpg",
  "طابع بريد": "house/طابع بريد.png",
  طابوق: "house/طابوق.png",
  طباخ: "house/طباخ.png",
  طبلة: "house/طبلة.png",
  ظرف: "house/ظرف.png",
  عصارة: "house/عصارة.png",
  عمارة: "house/عمارة.png",
  "غرفة الصالة": "house/غرفة الصالة.jpg",
  "غرفة النوم": "house/غرفة النوم.png",
  "غسالة الملابس": "house/غسالة الملابس.jpg",
  فستان: "house/فستان.png",
  فيديو: "house/فيديو.png",
  قميص: "house/قميص.png",
  كاسيت: "house/كاسيت.png",
  كاميرا: "house/كاميرا.png",
  كرسي: "house/كرسي.png",
  كوب: "house/كوب.png",
  "لوحة ": "house/لوحة .png",
  "مائدة طعام": "house/مائدة طعام.png",
  "ماكنة خياطة": "house/ماكنة خياطة.png",
  "ماكنة لحم": "house/ماكنة لحم.png",
  مدفاة: "house/مدفاة.png",
  مراة: "house/مراة.png",
  مروحة: "house/مروحة.png",
  مزهرية: "house/مزهرية.jpg",
  مسجل: "house/مسجل.png",
  مطبخ: "house/مطبخ.png",
  مطرقة: "house/مطرقة.png",
  مظلة: "house/مظلة.jpg",
  مفتاح: "house/مفتاح.png",
  مقص: "house/مقص.png",
  مكتب: "house/مكتب.png",
  مكنسة: "house/مكنسة.jpg",
  مكواة: "house/مكواة.png",
  ملعقة: "house/ملعقة.png",
  منشار: "house/منشار.png",
  مهد: "house/مهد.png",
  وسادة: "house/وسادة.png",
  باذنجان: "vegetables/باذنجان.png",
  بازليا: "vegetables/بازليا.jpg",
  باقلاء: "vegetables/باقلاء.png",
  بامية: "vegetables/بامية.jpg",
  برتقال: "vegetables/برتقال.png",
  بصل: "vegetables/بصل.png",
  بطاطا: "vegetables/بطاطا.png",
  بطيخ: "vegetables/بطيخ.png",
  تفاح: "vegetables/تفاح.png",
  تمر: "vegetables/تمر.png",
  تين: "vegetables/تين.png",
  ثوم: "vegetables/ثوم.png",
  جزر: "vegetables/جزر.png",
  "جوز الهند": "vegetables/جوز الهند.png",
  جوز: "vegetables/جوز.jpg",
  حمص: "vegetables/حمص.png",
  حنطة: "vegetables/حنطة.png",
  خس: "vegetables/خس.png",
  خضراوات: "vegetables/خضراوات.png",
  خوخ: "vegetables/خوخ.png",
  خيار: "vegetables/خيار.png",
  ذرة: "vegetables/ذرة.png",
  رز: "vegetables/رز.png",
  رقي: "vegetables/رقي.png",
  رمان: "vegetables/رمان.jpg",
  زبيب: "vegetables/زبيب.png",
  زيتون: "vegetables/زيتون.jpg",
  سبانغ: "vegetables/سبانغ.jpg",
  سلق: "vegetables/سلق.png",
  شجر: "vegetables/شجر.png",
  شعير: "vegetables/شعير.png",
  شوندر: "vegetables/شوندر.png",
  طماطة: "vegetables/طماطة.png",
  عرموط: "vegetables/عرموط.jpg",
  عنب: "vegetables/عنب.png",
  "فاصوليا بيضاء": "vegetables/فاصوليا بيضاء.png",
  "فاوصوليا خضراء": "vegetables/فاوصوليا خضراء.png",
  فجل: "vegetables/فجل.png",
  فلفل: "vegetables/فلفل.jpg",
  فواكه: "vegetables/فواكه.png",
  قرنابيط: "vegetables/قرنابيط.png",
  كرفس: "vegetables/كرفس.jpg",
  لالنكي: "vegetables/لالنكي.png",
  لهانة: "vegetables/لهانة.jpg",
  ليمون: "vegetables/ليمون.jpg",
  مشمش: "vegetables/مشمش.jpg",
  موز: "vegetables/موز.png",
  نعناع: "vegetables/نعناع.png",
  "الدورة العربية الرياضية": "sport/الدورة العربية الرياضية.jpg",
  اولمبياد: "sport/اولمبياد.png",
  بطولة: "sport/بطولة.jpg",
  بولنك: "sport/بولنك.png",
  تايكواندو: "sport/تايكواندو.jpg",
  "تزحلق على الجليد": "sport/تزحلق على الجليد.jpg",
  "تسلق الجبال": "sport/تسلق الجبال.png",
  تسلل: "sport/تسلل.jpg",
  "تمارين رياضية": "sport/تمارين رياضية.png",
  جائزة: "sport/جائزة.png",
  جمناستك: "sport/جمناستك.jpg",
  جودو: "sport/جودو.jpg",
  خسارة: "sport/خسارة.jpg",
  "خط الابيض": "sport/خط الابيض.png",
  "رفع الاثقال": "sport/رفع الاثقال.png",
  "رمي الرمح": "sport/رمي الرمح.png",
  "ساحة وميدان": "sport/ساحة وميدان.jpg",
  سباحة: "sport/سباحة.png",
  "سباق الدراجات النارية": "sport/سباق الدراجات النارية.png",
  "سباق الدراجات الهوائية": "sport/سباق الدراجات الهوائية.png",
  "سباق السيارات": "sport/سباق السيارات.jpg",
  "سباق رياضي": "sport/سباق رياضي.jpg",
  سنتر: "sport/سنتر.png",
  شبكة: "sport/شبكة.png",
  شطرنج: "sport/شطرنج.png",
  صافرة: "sport/صافرة.png",
  "فريق رياضي": "sport/فريق رياضي.jpg",
  فوز: "sport/فوز.png",
  كاراتيه: "sport/كاراتيه.png",
  "كاس البطولة": "sport/كاس البطولة.png",
  "كرة السلة": "sport/كرة السلة.png",
  "كرة الطائرة": "sport/كرة الطائرة.jpg",
  "كرة القدم": "sport/كرة القدم.png",
  "كرة المنضدة": "sport/كرة المنضدة.png",
  "كرة اليد": "sport/كرة اليد.jpg",
  "كمال الاجسام": "sport/كمال الاجسام.png",
  "مباراة رياضية": "sport/مباراة رياضية.png",
  مدرب: "sport/مدرب.png",
  مرمى: "sport/مرمى.png",
  مصارعة: "sport/مصارعة.png",
  ملاكمة: "sport/ملاكمة.png",
  ملعب: "sport/ملعب.png",
  "مهرجان رياضي": "sport/مهرجان رياضي.png",
  نادي: "sport/نادي.png",
  هدف: "sport/هدف.png",
  اب: "greetings/اب.png",
  ابن: "greetings/ابن.jpg",
  اخ: "greetings/اخ.jpg",
  اخت: "greetings/اخت.png",
  ارجو: "greetings/ارجو.png",
  اسرة: "greetings/اسرة.png",
  اسف: "greetings/اسف.png",
  اشخاص: "greetings/اشخاص.png",
  اقارب: "greetings/اقارب.png",
  ام: "greetings/ام.png",
  "اهلا وسهلا": "greetings/اهلا وسهلا.png",
  "بنت صغيرة": "greetings/بنت صغيرة.jpg",
  "تحية وسلام": "greetings/تحية وسلام.jpg",
  تفضل: "greetings/تفضل.png",
  توام: "greetings/توام.png",
  جد: "greetings/جد.png",
  جدة: "greetings/جدة.jpg",
  جيران: "greetings/جيران.png",
  خال: "greetings/خال.png",
  خالة: "greetings/خالة.png",
  خطوبة: "greetings/خطوبة.png",
  زواج: "greetings/زواج.png",
  زوج: "greetings/زوج.png",
  زوجة: "greetings/زوجة.png",
  "سلام عليكم": "greetings/سلام عليكم.png",
  شاب: "greetings/شاب.jpg",
  شابة: "greetings/شابة.jpg",
  شخص: "greetings/شخص.jpg",
  شعب: "greetings/شعب.jpg",
  شكرا: "greetings/شكرا.png",
  "صباح الخير": "greetings/صباح الخير.jpg",
  صبي: "greetings/صبي.jpg",
  ضيف: "greetings/ضيف.png",
  "طفل رضيع": "greetings/طفل رضيع.png",
  طلاق: "greetings/طلاق.png",
  عائلة: "greetings/عائلة.png",
  عجوز: "greetings/عجوز.png",
  عروسة: "greetings/عروسة.png",
  عريس: "greetings/عريس.jpg",
  "عليكم السلام": "greetings/عليكم السلام.png",
  عم: "greetings/عم.png",
  عمة: "greetings/عمة.jpg",
  "كيف الصحة": "greetings/كيف الصحة.png",
  "مع السلامة": "greetings/مع السلامة.jpg",
  ناس: "greetings/ناس.png",
  ولادة: "greetings/ولادة.png",
  "ولد صغير": "greetings/ولد صغير.png",
  اتحاد: "math/اتحاد.JPG",
  احتكاك: "science/احتكاك.png",
  "احياء بسيطة": "science/احياء بسيطة.png",
  "ارض خصبة": "science/ارض خصبة.png",
  ارض: "science/ارض.png",
  "اشارات ضوئية": "science/اشارات ضوئية.png",
  اشعة: "science/اشعة.png",
  "اشياء حية": "science/اشياء حية.jpg",
  "اشياء غير حية": "science/اشياء غير حية.png",
  "اطراف سفلى": "science/اطراف سفلى.jpg",
  "اطراف عليا": "science/اطراف عليا.png",
  اقتلاع: "science/اقتلاع.png",
  "الاتجاهات الاربعة": "science/الاتجاهات الاربعة.png",
  المنيوم: "science/المنيوم.jpg",
  "امعاء دقيقة": "science/امعاء دقيقة.png",
  "امعاء غليظة": "science/امعاء غليظة.jpg",
  انصهار: "science/انصهار.jpg",
  انعكاس: "science/انعكاس.jpg",
  انف: "science/انف.png",
  انكسار: "science/انكسار.png",
  بالونة: "science/بالونة.png",
  بخار: "science/بخار.png",
  بذرة: "science/بذرة.jpg",
  "برج مراقبة": "science/برج مراقبة.jpg",
  برق: "science/برق.png",
  بضائع: "science/بضائع.png",
  "بطارية السيارة": "science/بطارية السيارة.png",
  "بطارية جافة": "science/بطارية جافة.png",
  بكتريا: "science/بكتريا.jpg",
  بلعوم: "science/بلعوم.png",
  بنزين: "science/بنزين.png",
  بوصلة: "science/بوصلة.png",
  بيئة: "science/بيئة.png",
  تجاذب: "science/تجاذب.png",
  تجربة: "science/تجربة.jpg",
  "تحليل الدم": "science/تحليل الدم.png",
  "تحليل طبي": "science/تحليل طبي.jpg",
  تراب: "science/تراب.png",
  تربة: "science/تربة.png",
  تصفية: "science/تصفية.png",
  تعليمات: "science/تعليمات.png",
  "تكاثر الحيوان": "science/تكاثر الحيوان.png",
  "تكاثر نبات": "science/تكاثر نبات.jpg",
  تكنولوجيا: "science/تكنولوجيا.png",
  "تلقيح ": "science/تلقيح .png",
  "تلوث البيئة": "science/تلوث البيئة.png",
  "تلوث التربة": "science/تلوث التربة.png",
  "تلوث هواء": "science/تلوث هواء.jpg",
  تنافر: "science/تنافر.png",
  تنقيب: "science/تنقيب.png",
  ثقب: "science/ثقب.png",
  ثلج: "science/ثلج.png",
  ثمرة: "science/ثمرة.png",
  جاذبية: "science/جاذبية.png",
  جبن: "science/جبن.png",
  جدول: "computer/جدول.png",
  "جذر ليفي": "science/جذر ليفي.png",
  "جذر وتدي": "science/جذر وتدي.jpg",
  جذر: "math/جذر.JPG",
  جرح: "science/جرح.png",
  "جسم الانسان": "science/جسم الانسان.jpg",
  جلد: "science/جلد.png",
  جمجمة: "science/جمجمة.png",
  جنوب: "science/جنوب.png",
  "جهاز العظمي": "science/جهاز العظمي.png",
  "جهاز الهضمي": "science/جهاز الهضمي.png",
  "جهاز تسخين": "science/جهاز تسخين.png",
  "جهاز تنفسي": "science/جهاز تنفسي.jpg",
  جو: "science/جو.png",
  حافلة: "science/حافلة.png",
  "حالة سائلة": "science/حالة سائلة.png",
  "حالة صلبة": "science/حالة صلبة.png",
  "حالة غازية": "science/حالة غازية.jpg",
  "حبل الشوكي": "science/حبل الشوكي.png",
  حبوب: "science/حبوب.png",
  حجر: "science/حجر.jpg",
  "حديقة حيوانات": "science/حديقة حيوانات.png",
  "حديقة عامة": "science/حديقة عامة.jpg",
  حديقة: "science/حديقة.png",
  حراشف: "science/حراشف.png",
  حرير: "science/حرير.png",
  "حزمة ضوئية متجمعة": "science/حزمة ضوئية متجمعة.jpg",
  "حزمة ضوئية متفرقة": "science/حزمة ضوئية متفرقة.jpg",
  "حزمة ضوئية متوازية": "science/حزمة ضوئية متوازية.jpg",
  "حزمة ضوئية": "science/حزمة ضوئية.png",
  حشيش: "science/حشيش.jpg",
  حصو: "science/حصو.png",
  حطب: "science/حطب.png",
  حلي: "science/حلي.png",
  حليب: "science/حليب.png",
  "حواس الخمسة": "science/حواس الخمسة.jpg",
  "حيوانات اليفة": "science/حيوانات اليفة.png",
  "حيوانات برية": "science/حيوانات برية.jpg",
  "حيوانات غير اليفة": "science/حيوانات غير اليفة.png",
  "حيوانات لبونة": "science/حيوانات لبونة.png",
  خبز: "science/خبز.png",
  خريف: "science/خريف.png",
  "خزان وقود": "science/خزان وقود.png",
  "خسوف القمر": "science/خسوف القمر.jpg",
  خشب: "science/خشب.jpg",
  خياشيم: "science/خياشيم.png",
  دخان: "science/دخان.jpg",
  "درجة الحرارة": "science/درجة الحرارة.png",
  دواء: "science/دواء.png",
  "دوران الدم": "science/دوران الدم.png",
  "دورة الماء": "science/دورة الماء.png",
  ذوبان: "science/ذوبان.png",
  رئتان: "science/رئتان.png",
  رائحة: "science/رائحة.png",
  رافعة: "science/رافعة.png",
  ربيع: "science/ربيع.png",
  ريح: "science/ريح.png",
  ريش: "science/ريش.jpg",
  زبدة: "science/زبدة.png",
  زعانف: "science/زعانف.png",
  زفير: "science/زفير.png",
  زلزال: "science/زلزال.png",
  زهرة: "science/زهرة.jpg",
  "ساق زاحفة": "science/ساق زاحفة.png",
  "ساق قائمة": "science/ساق قائمة.png",
  ساق: "science/ساق.png",
  سحاب: "science/سحاب.jpg",
  سكر: "science/سكر.png",
  "سلسلة غذائية": "science/سلسلة غذائية.png",
  "سلك كهربائي": "science/سلك كهربائي.jpg",
  سم: "science/سم.png",
  سماء: "science/سماء.png",
  سنارة: "science/سنارة.png",
  شاحنة: "science/شاحنة.png",
  "شباك الصيد": "science/شباك الصيد.jpg",
  شتاء: "science/شتاء.png",
  شجرة: "science/شجرة.png",
  شرق: "science/شرق.png",
  شعر: "science/شعر.png",
  شمال: "science/شمال.png",
  شمس: "science/شمس.png",
  شمعة: "science/شمعة.png",
  شهيق: "science/شهيق.jpg",
  صحة: "science/صحة.png",
  صداع: "science/صداع.png",
  صفيح: "science/صفيح.png",
  صوت: "science/صوت.png",
  "صوف الخروف": "science/صوف الخروف.png",
  صيف: "science/صيف.png",
  ضباب: "science/ضباب.png",
  ضغط: "science/ضغط.png",
  ضوء: "science/ضوء.png",
  طائف: "science/طائف.jpg",
  طاحونة: "science/طاحونة.png",
  طبيعة: "science/طبيعة.jpg",
  طحالب: "science/طحالب.jpg",
  طحين: "science/طحين.png",
  طين: "science/طين.jpg",
  ظل: "science/ظل.jpg",
  عاصفة: "science/عاصفة.png",
  عجين: "science/عجين.png",
  "عدسة محدبة": "science/عدسة محدبة.png",
  "عدسة مقعرة": "science/عدسة مقعرة.png",
  عش: "science/عش.jpg",
  عشب: "science/عشب.png",
  عصير: "science/عصير.jpg",
  "عضلات ارادية": "science/عضلات ارادية.png",
  "عضلات لا ارادية": "science/عضلات لا ارادية.jpg",
  "عظم مجوف": "science/عظم مجوف.jpg",
  عظم: "science/عظم.png",
  "عملية جراحية": "science/عملية جراحية.png",
  "عمود الفقري": "science/عمود الفقري.jpg",
  عنصر: "science/عنصر.png",
  غابة: "science/غابة.png",
  غاز: "science/غاز.png",
  غرب: "science/غرب.png",
  غزل: "science/غزل.png",
  غصن: "science/غصن.png",
  فحم: "science/فحم.png",
  فراغ: "science/فراغ.png",
  "فصول الاربعة": "science/فصول الاربعة.png",
  فضة: "science/فضة.jpg",
  فطريات: "science/فطريات.png",
  "فقر الدم": "science/فقر الدم.png",
  فلين: "science/فلين.png",
  فم: "science/فم.png",
  قالب: "science/قالب.png",
  قشور: "science/قشور.png",
  "قصبة الهوائية": "science/قصبة الهوائية.png",
  قطرة: "science/قطرة.png",
  قطن: "science/قطن.png",
  قلب: "science/قلب.jpg",
  قمامة: "science/قمامة.jpg",
  قمر: "science/قمر.png",
  قوة: "science/قوة.png",
  "قوس قزح": "science/قوس قزح.jpg",
  كبد: "science/كبد.png",
  "كسوف الشمس": "science/كسوف الشمس.png",
  كلية: "country/كلية.JPG",
  كمية: "science/كمية.png",
  كهرباء: "science/كهرباء.jpg",
  كهف: "science/كهف.jpg",
  كيمياء: "science/كيمياء.png",
  لبن: "science/لبن.png",
  لحم: "science/لحم.png",
  "مبيدات حشرية": "science/مبيدات حشرية.png",
  مجذاف: "science/مجذاف.png",
  مجوف: "science/مجوف.png",
  محرار: "science/محرار.png",
  "محطة وقود": "science/محطة وقود.png",
  مخلوط: "science/مخلوط.png",
  مركب: "science/مركب.png",
  مزرعة: "science/مزرعة.png",
  مستنقع: "science/مستنقع.jpg",
  "مصباح كهربائي": "science/مصباح كهربائي.png",
  "مصباح نفطي": "science/مصباح نفطي.jpg",
  "مصباح يدوي": "science/مصباح يدوي.png",
  مصباح: "science/مصباح.png",
  مصدر: "science/مصدر.png",
  مطاط: "science/مطاط.png",
  مطر: "science/مطر.png",
  "مظاهر الحياة": "science/مظاهر الحياة.png",
  معادن: "science/معادن.png",
  معدة: "science/معدة.png",
  مغمور: "science/مغمور.png",
  مغناطيس: "science/مغناطيس.png",
  ملح: "science/ملح.png",
  "ملف كهربائي": "science/ملف كهربائي.png",
  "منطقة قطبية": "science/منطقة قطبية.jpg",
  منقار: "science/منقار.png",
  "مواد كيميواوية": "science/مواد كيميواوية.jpg",
  موج: "science/موج.png",
  "مياه جارية": "science/مياه جارية.png",
  "مياه ساقطة": "science/مياه ساقطة.jpg",
  نار: "science/نار.jpg",
  "ناقلة وقود": "science/ناقلة وقود.jpg",
  "نبضات القلب": "science/نبضات القلب.jpg",
  نحاس: "science/نحاس.png",
  ندى: "science/ندى.png",
  نزهة: "science/نزهة.jpg",
  "نزيف الدم": "science/نزيف الدم.jpg",
  نسمة: "science/نسمة.png",
  نفط: "science/نفط.jpg",
  "نقود معدنية": "science/نقود معدنية.jpg",
  نهر: "science/نهر.png",
  "هضم الطعام": "science/هضم الطعام.png",
  هلال: "science/هلال.png",
  هواء: "science/هواء.png",
  "هيكل عظمي": "science/هيكل عظمي.jpg",
  "وبر الابل": "science/وبر الابل.jpg",
  "ورق نشاف": "science/ورق نشاف.png",
  ورقة: "science/ورقة.png",
  وقود: "science/وقود.png",
  ينبوع: "science/ينبوع.png",
  ابيض: "arts/ابيض.png",
  احمر: "arts/احمر.png",
  اخضر: "arts/اخضر.png",
  ازرق: "arts/ازرق.png",
  اسود: "arts/اسود.png",
  اصفر: "arts/اصفر.png",
  اغنية: "arts/اغنية.png",
  اكورديون: "arts/اكورديون.png",
  "الوان مائية": "arts/الوان مائية.png",
  الوان: "arts/الوان.png",
  برتقالي: "arts/برتقالي.png",
  بنفسجي: "arts/بنفسجي.jpg",
  بوق: "arts/بوق.png",
  تصميم: "arts/تصميم.png",
  تصوير: "arts/تصوير.png",
  تمثيلية: "arts/تمثيلية.png",
  حفلة: "arts/حفلة.png",
  دف: "arts/دف.png",
  رسالة: "arts/رسالة.jpg",
  رصاصي: "arts/رصاصي.png",
  "رقصة باليه": "arts/رقصة باليه.jpg",
  زخرفة: "arts/زخرفة.png",
  سيراميك: "arts/سيراميك.jpg",
  سينما: "arts/سينما.png",
  شفاف: "arts/شفاف.png",
  طبل: "arts/طبل.png",
  غامق: "arts/غامق.png",
  فاتح: "arts/فاتح.png",
  فلم: "arts/فلم.png",
  فن: "arts/فن.png",
  قصة: "arts/قصة.png",
  متحف: "arts/متحف.png",
  مزمار: "arts/مزمار.png",
  مسرح: "arts/مسرح.png",
  مسلسل: "arts/مسلسل.png",
  معرض: "arts/معرض.png",
  موسيقى: "arts/موسيقى.png",
  نحت: "arts/نحت.png",
  وردي: "arts/وردي.png",
  ادراج: "computer/ادراج.png",
  "اعادة التشغيل": "computer/اعادة التشغيل.png",
  انترنيت: "computer/انترنيت.png",
  برنامج: "computer/برنامج.png",
  تضليل: "computer/تضليل.png",
  تنسيق: "computer/تنسيق.png",
  "جهاز حماية (UPS)": "computer/جهاز حماية (UPS).png",
  حذف: "computer/حذف.png",
  رمز: "computer/رمز.png",
  "سطح المكتب": "computer/سطح المكتب.png",
  سكنر: "computer/سكنر.png",
  "سلة المحذوفات": "computer/سلة المحذوفات.png",
  شاشة: "computer/شاشة.png",
  طابعة: "computer/طابعة.png",
  "فرز البيانات": "computer/فرز البيانات.png",
  "قرص صلب": "computer/قرص صلب.png",
  "قرص مرن": "computer/قرص مرن.png",
  كمبيوتر: "school/كمبيوتر.png",
  كيبورد: "computer/كيبورد.jpg",
  كيس: "computer/كيس.png",
  "لوحة مفاتيح": "computer/لوحة مفاتيح.png",
  ماوس: "computer/ماوس.png",
  "مفتاح البداية": "computer/مفتاح البداية.png",
  "مفتاح الحذف": "computer/مفتاح الحذف.png",
  "مفتاح الحشر": "computer/مفتاح الحشر.png",
  "مفتاح العالي": "computer/مفتاح العالي.png",
  "مفتاح النهاية": "computer/مفتاح النهاية.jpg",
  "مفتاح الهروب -ESC": "computer/مفتاح الهروب -ESC.png",
  "مفتاح تبديل": "computer/مفتاح تبديل.jpg",
  ملف: "computer/ملف.jpg",
  اجازة: "school/اجازة.png",
  "اعمال فنية": "school/اعمال فنية.png",
  امتحان: "school/امتحان.png",
  تاريخ: "school/تاريخ.png",
  "جدول الدروس": "school/جدول الدروس.jpg",
  جغرافية: "school/جغرافية.png",
  حقيبة: "school/حقيبة.png",
  "داوم رسمي": "school/داوم رسمي.png",
  دفتر: "school/دفتر.png",
  رياضة: "school/رياضة.png",
  رياضيات: "school/رياضيات.png",
  سبورة: "school/سبورة.png",
  "سفرة مدرسية": "school/سفرة مدرسية.png",
  شهادة: "school/شهادة.png",
  صف: "school/صف.jpg",
  صمغ: "school/صمغ.png",
  طباشير: "school/طباشير.png",
  "عطلة رسمية": "school/عطلة رسمية.png",
  علوم: "school/علوم.png",
  "قلم ملون": "school/قلم ملون.jpg",
  قلم: "school/قلم.png",
  كتاب: "school/كتاب.png",
  لاصق: "school/لاصق.jpg",
  "لغة انكليزية": "school/لغة انكليزية.png",
  "لغة عربية": "school/لغة عربية.jpg",
  مبراة: "school/مبراة.png",
  محفظة: "school/محفظة.png",
  مدرسة: "school/مدرسة.png",
  "مرحلة ابتدائية": "school/مرحلة ابتدائية.jpg",
  "مرحلة اعدادية": "school/مرحلة اعدادية.png",
  "مرحلة متوسطة": "school/مرحلة متوسطة.png",
  مسطرة: "school/مسطرة.png",
  مكتبة: "school/مكتبة.png",
  ممحاة: "school/ممحاة.png",
  وطنية: "school/وطنية.png",
  "ابن السبيل": "relgion/ابن السبيل.jpg",
  "ابو بكر": "relgion/ابو بكر.JPG",
  "احياء الموتى": "relgion/احياء الموتى.JPG",
  ادم: "relgion/ادم.jpg",
  اذان: "relgion/اذان.JPG",
  "اركان الاسلام": "relgion/اركان الاسلام.jpg",
  "اركان الايمان": "relgion/اركان الايمان.jpg",
  اعبد: "relgion/اعبد.JPG",
  "اعوذ بالله من الشيطان الرجيم": "relgion/اعوذ بالله من الشيطان الرجيم.jpg",
  "الاسراء والمعراج": "relgion/الاسراء والمعراج.jpg",
  "الحمد لله": "relgion/الحمد لله.jpg",
  "السيرة النبوية": "relgion/السيرة النبوية.JPG",
  الشهادة: "relgion/الشهادة.JPG",
  الكعبة: "relgion/الكعبة.JPG",
  "الله احد": "relgion/الله احد.JPG",
  "الله الصمد": "relgion/الله الصمد.JPG",
  "المدينة المنورة": "relgion/المدينة المنورة.jpg",
  "الهجرة النبوية": "relgion/الهجرة النبوية.jpg",
  امام: "relgion/امام.JPG",
  امانة: "relgion/امانة.JPG",
  انجيل: "relgion/انجيل.JPG",
  "اولي العزم": "relgion/اولي العزم.jpg",
  "اياك نستعين": "relgion/اياك نستعين.JPG",
  "اياك نعبد": "relgion/اياك نعبد.JPG",
  اية: "relgion/اية.JPG",
  "ايمان بالاخرة": "relgion/ايمان بالاخرة.jpg",
  "ايمان بالرسل": "relgion/ايمان بالرسل.JPG",
  "ايمان بالكتب": "relgion/ايمان بالكتب.JPG",
  "ايمان بالله": "relgion/ايمان بالله.jpg",
  "ايمان بالملائكة": "relgion/ايمان بالملائكة.JPG",
  ايمان: "relgion/ايمان.JPG",
  بركة: "relgion/بركة.JPG",
  "بسم الله الرحمن الرحيم": "relgion/بسم الله الرحمن الرحيم.jpg",
  بشير: "relgion/بشير.JPG",
  "بعث الرسالة الاسلامية": "relgion/بعث الرسالة الاسلامية.JPG",
  تسليم: "relgion/تسليم.jpg",
  توبة: "relgion/توبة.JPG",
  توراة: "relgion/توراة.JPG",
  تيمم: "relgion/تيمم.jpg",
  ثواب: "relgion/ثواب.jpg",
  جبرائيل: "relgion/جبرائيل.jpg",
  "جبل عرفات": "relgion/جبل عرفات.JPG",
  جن: "relgion/جن.JPG",
  جنة: "relgion/جنة.jpg",
  "جهاد في سبيل الله": "relgion/جهاد في سبيل الله.jpg",
  جهنم: "relgion/جهنم.jpg",
  حاسد: "relgion/حاسد.JPG",
  حج: "relgion/حج.JPG",
  حرام: "relgion/حرام.JPG",
  حساب: "relgion/حساب.JPG",
  "حسن المعاشرة": "relgion/حسن المعاشرة.JPG",
  حق: "relgion/حق.JPG",
  "حقوق الوالدين": "relgion/حقوق الوالدين.jpg",
  حلال: "relgion/حلال.JPG",
  حلم: "relgion/حلم.JPG",
  حماس: "relgion/حماس.JPG",
  حنث: "relgion/حنث.jpg",
  حواء: "relgion/حواء.jpg",
  "خطبة الجمعة": "relgion/خطبة الجمعة.jpg",
  خطيب: "relgion/خطيب.JPG",
  "خلفاء الراشدين": "relgion/خلفاء الراشدين.jpg",
  خلق: "relgion/خلق.JPG",
  دعاء: "relgion/دعاء.JPG",
  "دعوة اسلامية": "relgion/دعوة اسلامية.jpg",
  "دعوة سرية": "relgion/دعوة سرية.JPG",
  "دعوة علنية": "relgion/دعوة علنية.JPG",
  "دين اسلامي": "relgion/دين اسلامي.JPG",
  "دين صابئي": "relgion/دين صابئي.JPG",
  "دين مسيحي": "relgion/دين مسيحي.JPG",
  "دين يهودي": "relgion/دين يهودي.JPG",
  ذنب: "relgion/ذنب.JPG",
  "رب الفلق": "relgion/رب الفلق.jpg",
  رحمة: "relgion/رحمة.JPG",
  رسول: "relgion/رسول.JPG",
  "رضا الله": "relgion/رضا الله.jpg",
  روح: "relgion/روح.jpg",
  زبور: "relgion/زبور.jpg",
  زكاة: "relgion/زكاة.jpg",
  "سبحان الله": "relgion/سبحان الله.JPG",
  "سورة الفاتحة": "relgion/سورة الفاتحة.jpg",
  "سورة النبا": "relgion/سورة النبا.jpg",
  سورة: "relgion/سورة.JPG",
  "شر النفاثات من العقد": "relgion/شر النفاثات من العقد.JPG",
  "شر غاسق": "relgion/شر غاسق.JPG",
  "شر ما خلق": "relgion/شر ما خلق.JPG",
  "شر ماخلق": "relgion/شر ماخلق.JPG",
  "شرك بالله": "relgion/شرك بالله.jpg",
  شيطان: "relgion/شيطان.JPG",
  "صراط المستقيم": "relgion/صراط المستقيم.JPG",
  "صفا ومروة": "relgion/صفا ومروة.jpg",
  "صلاة الظهر": "relgion/صلاة الظهر.JPG",
  "صلاة العشاء": "relgion/صلاة العشاء.JPG",
  "صلاة العصر": "relgion/صلاة العصر.jpg",
  "صلاة الفجر": "relgion/صلاة الفجر.JPG",
  "صلاة المغرب": "relgion/صلاة المغرب.jpg",
  صلاة: "relgion/صلاة.JPG",
  "صلى الله عليه وسلم": "relgion/صلى الله عليه وسلم.jpg",
  صنم: "relgion/صنم.JPG",
  صوم: "relgion/صوم.JPG",
  ضالون: "relgion/ضالون.JPG",
  "طريق الحق": "relgion/طريق الحق.jpg",
  طواف: "relgion/طواف.JPG",
  "ظن سيء": "relgion/ظن سيء.jpg",
  "عالم الغيب": "relgion/عالم الغيب.jpg",
  عبادة: "relgion/عبادة.JPG",
  "عثمان بن عفان": "relgion/عثمان بن عفان.jpg",
  عذاب: "relgion/عذاب.JPG",
  "عقاب وجزاء": "relgion/عقاب وجزاء.jpg",
  عقاب: "relgion/عقاب.jpg",
  "عقوق الوالدين": "relgion/عقوق الوالدين.jpg",
  "علي ابن ابي طالب": "relgion/علي ابن ابي طالب.jpg",
  "عمر ابن الخطاب": "relgion/عمر ابن الخطاب.JPG",
  عمرة: "relgion/عمرة.JPG",
  "عيد الاضحى": "relgion/عيد الاضحى.jpg",
  "عيد الفطر": "relgion/عيد الفطر.JPG",
  "عيد راس السنة الهجري": "relgion/عيد راس السنة الهجري.JPG",
  "عيد ميلاد المسيح": "relgion/عيد ميلاد المسيح.JPG",
  غفران: "relgion/غفران.JPG",
  فريضة: "relgion/فريضة.jpg",
  قبلة: "relgion/قبلة.jpg",
  "قدرة الله": "relgion/قدرة الله.jpg",
  قدس: "relgion/قدس.JPG",
  "قران كريم": "relgion/قران كريم.jpg",
  "قسم وحلف": "relgion/قسم وحلف.jpg",
  "قضاء وقدر": "relgion/قضاء وقدر.JPG",
  كافرون: "relgion/كافرون.jpg",
  "كف الاذى": "relgion/كف الاذى.JPG",
  كفر: "relgion/كفر.JPG",
  كفن: "relgion/كفن.JPG",
  كفوا: "relgion/كفوا.JPG",
  كنيسة: "relgion/كنيسة.jpg",
  "لم يلد": "relgion/لم يلد.JPG",
  "ليلة القدر": "relgion/ليلة القدر.jpg",
  "ماء زمزم": "relgion/ماء زمزم.JPG",
  "مالك يوم الدين": "relgion/مالك يوم الدين.jpg",
  مبارك: "relgion/مبارك.JPG",
  "محاسن الاخلاق": "relgion/محاسن الاخلاق.JPG",
  "مدفع الافطار": "relgion/مدفع الافطار.jpg",
  مسجد: "relgion/مسجد.JPG",
  معروف: "relgion/معروف.jpg",
  "مغضوب عليهم": "relgion/مغضوب عليهم.jpg",
  مقدس: "relgion/مقدس.JPG",
  منبر: "relgion/منبر.JPG",
  "مولد النبوي": "relgion/مولد النبوي.JPG",
  "نبي ابراهيم": "relgion/نبي ابراهيم.JPG",
  "نبي عيسى": "relgion/نبي عيسى.jpg",
  "نبي محمد": "relgion/نبي محمد.jpg",
  "نبي موسى": "relgion/نبي موسى.jpg",
  "نبي نوح": "relgion/نبي نوح.JPG",
  نبي: "relgion/نبي.JPG",
  نذير: "relgion/نذير.jpg",
  نعمة: "relgion/نعمة.JPG",
  نميمة: "relgion/نميمة.JPG",
  نية: "relgion/نية.JPG",
  "هدى الله": "relgion/هدى الله.JPG",
  وضوء: "relgion/وضوء.JPG",
  "وقفة عرفات": "relgion/وقفة عرفات.jpg",
  يهدي: "relgion/يهدي.JPG",
  "يوم القيامة": "relgion/يوم القيامة.jpg",
  "12-1": "math/12-1.JPG",
  "12-2": "math/12-2.JPG",
  "15-1": "math/15-1.JPG",
  "2000-1": "math/2000-1.JPG",
  "31-1": "math/31-1.JPG",
  "31-2": "math/31-2.JPG",
  ابعد: "math/ابعد.JPG",
  ابعد1: "math/ابعد1.JPG",
  اثقل: "math/اثقل.JPG",
  احاد: "math/احاد.JPG",
  اخف: "math/اخف.JPG",
  ارتفاع: "math/ارتفاع.JPG",
  ارقام: "math/ارقام.JPG",
  اشكال: "math/اشكال.JPG",
  اطول: "math/اطول.JPG",
  "اعداد عشرية": "math/اعداد عشرية.JPG",
  اقرب: "math/اقرب.JPG",
  اقل: "math/اقل.JPG",
  اكثر: "math/اكثر.JPG",
  الوف: "math/الوف.JPG",
  اول: "math/اول.JPG",
  بسط: "math/بسط.JPG",
  تربيع: "math/تربيع.JPG",
  تربيع1: "math/تربيع1.JPG",
  تقاطع: "math/تقاطع.JPG",
  تكعيب: "math/تكعيب.JPG",
  تكعيب1: "math/تكعيب1.JPG",
  تمرين: "math/تمرين.JPG",
  ثالث: "math/ثالث.JPG",
  ثاني: "math/ثاني.JPG",
  ثقيل: "math/ثقيل.JPG",
  ثلثين: "math/ثلثين.JPG",
  ثمن: "math/ثمن.JPG",
  جزء: "math/جزء.JPG",
  جواب: "math/جواب.JPG",
  جواب1: "math/جواب1.JPG",
  حجم: "math/حجم.JPG",
  حجم1: "math/حجم1.JPG",
  خارج: "math/خارج.JPG",
  خامس: "math/خامس.JPG",
  "خط مستقيم": "math/خط مستقيم.JPG",
  خفيف: "math/خفيف.JPG",
  دائرة: "math/دائرة.JPG",
  داخل: "math/داخل.JPG",
  رابع: "math/رابع.JPG",
  ربع: "math/ربع.JPG",
  "زاوية حادة": "math/زاوية حادة.JPG",
  "زاوية قائمة": "math/زاوية قائمة.JPG",
  "زاوية مستقيمة": "math/زاوية مستقيمة.JPG",
  "زاوية منفرجة": "math/زاوية منفرجة.JPG",
  "زاوية منفرجة1": "math/زاوية منفرجة1.JPG",
  زاوية: "math/زاوية.JPG",
  سؤال: "math/سؤال.JPG",
  سطح: "math/سطح.JPG",
  سعة: "math/سعة.JPG",
  سلاسل: "math/سلاسل.JPG",
  سنتمتر: "math/سنتمتر.JPG",
  شعاع: "math/شعاع.JPG",
  "شكل رباعي": "math/شكل رباعي.JPG",
  صغير: "math/صغير.JPG",
  طرح: "math/طرح.JPG",
  طن: "math/طن.JPG",
  طن1: "math/طن1.JPG",
  "طول الضلع": "math/طول الضلع.JPG",
  "طول الضلع1": "math/طول الضلع1.JPG",
  طول: "math/طول.JPG",
  طويل: "math/طويل.JPG",
  "عامل مضاعف": "math/عامل مضاعف.JPG",
  عامل: "math/عامل.JPG",
  "عد تصاعدي": "math/عد تصاعدي.JPG",
  "عد تصاعدي1": "math/عد تصاعدي1.JPG",
  "عد تنازلي": "math/عد تنازلي.JPG",
  عرض: "math/عرض.JPG",
  عشرات: "math/عشرات.JPG",
  "عملة نقدية": "math/عملة نقدية.JPG",
  "عمليات الجمع": "math/عمليات الجمع.JPG",
  "عملية الضرب": "math/عملية الضرب.JPG",
  "عملية القسمة": "math/عملية القسمة.JPG",
  عناصر: "math/عناصر.JPG",
  عين: "math/عين.JPG",
  عين1: "math/عين1.JPG",
  غرام: "math/غرام.JPG",
  قارن: "math/قارن.JPG",
  قصير: "math/قصير.JPG",
  "قطر الدائرة": "math/قطر الدائرة.JPG",
  قليل: "math/قليل.JPG",
  قياسي: "math/قياسي.JPG",
  كبير: "math/كبير.JPG",
  كثير: "math/كثير.JPG",
  كم: "math/كم.JPG",
  "كيلو غرام": "math/كيلو غرام.JPG",
  "كيلو غرام1": "math/كيلو غرام1.JPG",
  لاينتمي: "math/لاينتمي.JPG",
  لاينتمي1: "math/لاينتمي1.JPG",
  لتر: "math/لتر.JPG",
  مئات: "math/مئات.JPG",
  "متر مربع": "math/متر مربع.JPG",
  "متر مكعب": "math/متر مكعب.JPG",
  "متر مكعب1": "math/متر مكعب1.JPG",
  متر: "math/متر.JPG",
  متشابه: "math/متشابه.JPG",
  متشابه1: "math/متشابه1.JPG",
  متطابق: "math/متطابق.JPG",
  "متوازي الاضلاع": "math/متوازي الاضلاع.JPG",
  مثلث: "math/مثلث.JPG",
  مجسمات: "math/مجسمات.JPG",
  "مجموعة خالية": "math/مجموعة خالية.JPG",
  مجموعة: "math/مجموعة.JPG",
  محيط: "math/محيط.JPG",
  مختلفة: "math/مختلفة.JPG",
  مخروط: "math/مخروط.JPG",
  مربع: "math/مربع.JPG",
  "مركز الدائرة": "math/مركز الدائرة.JPG",
  "مساحة جانبية": "math/مساحة جانبية.JPG",
  "مساحة جانبية1": "math/مساحة جانبية1.JPG",
  مساحة: "math/مساحة.JPG",
  مستطيل: "math/مستطيل.JPG",
  "مستقيمان متقاطعان": "math/مستقيمان متقاطعان.JPG",
  "مستقيمان متقاطعان1": "math/مستقيمان متقاطعان1.JPG",
  "مستقيمان متوازيان": "math/مستقيمان متوازيان.JPG",
  "مستقيمان متوازيان1": "math/مستقيمان متوازيان1.JPG",
  معين: "math/معين.JPG",
  مقام: "math/مقام.JPG",
  مكعب: "math/مكعب.JPG",
  مكعب1: "math/مكعب1.JPG",
  مليار: "math/مليار.JPG",
  مليار1: "math/مليار1.JPG",
  مليون: "math/مليون.JPG",
  مليونين: "math/مليونين.JPG",
  "منحني مغلق": "math/منحني مغلق.JPG",
  "منحني مفتوح": "math/منحني مفتوح.JPG",
  "منحني مفتوح1": "math/منحني مفتوح1.JPG",
  "نسبة وتناسب": "math/نسبة وتناسب.JPG",
  "نقطة بداية": "math/نقطة بداية.JPG",
  "نقطة نهاية": "math/نقطة نهاية.JPG",
  "نقطة نهاية1": "math/نقطة نهاية1.JPG",
  وزن: "math/وزن.JPG",
  يساوي: "math/يساوي.JPG",
  ينتمي: "math/ينتمي.JPG",
  باخرة: "transport/باخرة.png",
  باص: "transport/باص.png",
  "دراجة نارية": "transport/دراجة نارية.png",
  "دراجة هوائية": "transport/دراجة هوائية.png",
  زورق: "transport/زورق.png",
  "سفينة فضائية": "transport/سفينة فضائية.png",
  "سيارة اسعاف": "transport/سيارة اسعاف.png",
  "سيارة اطفاء": "transport/سيارة اطفاء.png",
  "سيارة نجدة": "transport/سيارة نجدة.jpg",
  سيارة: "transport/سيارة.png",
  طيارة: "transport/طيارة.png",
  عربة: "transport/عربة.png",
  قطار: "transport/قطار.png",
  مطار: "transport/مطار.png",
  ميناء: "transport/ميناء.jpg",
  ابداع: "country/ابداع.JPG",
  ازمة: "country/ازمة.JPG",
  اشتراكية: "country/اشتراكية.JPG",
  اكراد: "country/اكراد.JPG",
  "الامم المتحدة": "country/الامم المتحدة.JPG",
  انتماء: "country/انتماء.JPG",
  "ترشيد استهلاكي": "country/ترشيد استهلاكي.JPG",
  تركمان: "country/تركمان.JPG",
  تشريع: "country/تشريع.jpg",
  تضامن: "country/تضامن.JPG",
  تطور: "country/تطور.JPG",
  تنفيذ: "country/تنفيذ.jpg",
  تهريب: "country/تهريب.JPG",
  توحيد: "country/توحيد.jpg",
  جامعة: "country/جامعة.JPG",
  جمعية: "country/جمعية.JPG",
  حزب: "country/حزب.JPG",
  حضارة: "country/حضارة.jpg",
  حكومة: "country/حكومة.JPG",
  "دار الايتام": "country/دار الايتام.jpg",
  "دار المسنين": "country/دار المسنين.jpg",
  "دار حضانة": "country/دار حضانة.JPG",
  دستور: "country/دستور.jpg",
  "دفاع مدني": "country/دفاع مدني.JPG",
  دكتاتورية: "country/دكتاتورية.jpg",
  "رئيس جمعية": "country/رئيس جمعية.JPG",
  راسمالية: "country/راسمالية.jpg",
  روضة: "country/روضة.JPG",
  سفارة: "country/سفارة.JPG",
  سلطة: "country/سلطة.jpg",
  شركة: "country/شركة.JPG",
  طائفة: "country/طائفة.jpg",
  عاصمة: "country/عاصمة.JPG",
  عرب: "country/عرب.JPG",
  "عضو جمعية": "country/عضو جمعية.JPG",
  فخر: "country/فخر.jpg",
  قانون: "country/قانون.JPG",
  قضاء: "country/قضاء.JPG",
  قومية: "country/قومية.JPG",
  "مجلس النواب": "country/مجلس النواب.JPG",
  "مجلس بلدي": "country/مجلس بلدي.JPG",
  محافظة: "country/محافظة.JPG",
  "مسلة حمورابي": "country/مسلة حمورابي.jpg",
  "مكافحة اجرام": "country/مكافحة اجرام.jpg",
  منجزات: "country/منجزات.JPG",
  ناحية: "country/ناحية.JPG",
  "وزارة الاتصالات": "country/وزارة الاتصالات.JPG",
  "وزارة الاسكان": "country/وزارة الاسكان.JPG",
  "وزارة البلديات": "country/وزارة البلديات.jpg",
  "وزارة البيئة": "country/وزارة البيئة.JPG",
  "وزارة التجارة": "country/وزارة التجارة.JPG",
  "وزارة التخطيط": "country/وزارة التخطيط.jpg",
  "وزارة التربية": "country/وزارة التربية.JPG",
  "وزارة الخارجية": "country/وزارة الخارجية.JPG",
  "وزارة الداخلية": "country/وزارة الداخلية.jpg",
  "وزارة الزراعة": "country/وزارة الزراعة.JPG",
  "وزارة الشباب والرياضة": "country/وزارة الشباب والرياضة.JPG",
  "وزارة الصحة": "country/وزارة الصحة.JPG",
  "وزارة الصناعة": "country/وزارة الصناعة.jpg",
  "وزارة العدل": "country/وزارة العدل.JPG",
  "وزارة العلوم": "country/وزارة العلوم.jpg",
  "وزارة العمل": "country/وزارة العمل.jpg",
  "وزارة الكهرباء": "country/وزارة الكهرباء.jpg",
  "وزارة المالية": "country/وزارة المالية.jpg",
  "وزارة الموارد المالية": "country/وزارة الموارد المالية.jpg",
  "وزارة النفط": "country/وزارة النفط.JPG",
  "وزارة النقل": "country/وزارة النقل.jpg",
  "وزارة الهجرة": "country/وزارة الهجرة.JPG",
  "وزارة حقوق الانسان": "country/وزارة حقوق الانسان.JPG",
  وزارة: "country/وزارة.JPG",
  ولاء: "country/ولاء.JPG",
  اصيل: "adjectives/اصيل.JPG",
  امان: "adjectives/امان.JPG",
  بارد: "adjectives/بارد.JPG",
  بطئ: "adjectives/بطئ.JPG",
  بطل: "adjectives/بطل.JPG",
  بهجة: "adjectives/بهجة.JPG",
  تعبان: "adjectives/تعبان.JPG",
  ثابت: "adjectives/ثابت.JPG",
  ثرثار: "adjectives/ثرثار.JPG",
  جاد: "adjectives/جاد.JPG",
  جاف: "adjectives/جاف.JPG",
  جبان: "adjectives/جبان.JPG",
  جهل: "adjectives/جهل.jpg",
  حار: "adjectives/حار.JPG",
  حر: "adjectives/حر.jpg",
  حريص: "adjectives/حريص.JPG",
  حزين: "adjectives/حزين.JPG",
  حكيم: "adjectives/حكيم.jpg",
  حنين: "adjectives/حنين.JPG",
  خائف: "adjectives/خائف.JPG",
  خجول: "adjectives/خجول.JPG",
  خشن: "adjectives/خشن.JPG",
  خير: "adjectives/خير.JPG",
  ذكي: "adjectives/ذكي.JPG",
  راسب: "adjectives/راسب.jpg",
  رحيم: "adjectives/رحيم.JPG",
  رشيق: "adjectives/رشيق.JPG",
  رطب: "adjectives/رطب.jpg",
  رقيق: "adjectives/رقيق.JPG",
  ساحر: "adjectives/ساحر.jpg",
  ساخن: "adjectives/ساخن.JPG",
  ساهر: "adjectives/ساهر.jpg",
  سريع: "adjectives/سريع.JPG",
  سعيد: "adjectives/سعيد.JPG",
  سهل: "adjectives/سهل.JPG",
  شجاع: "adjectives/شجاع.JPG",
  شر: "adjectives/شر.JPG",
  شريف: "adjectives/شريف.JPG",
  شفاء: "adjectives/شفاء.JPG",
  شفقة: "adjectives/شفقة.JPG",
  صادق: "adjectives/صادق.JPG",
  صبر: "adjectives/صبر.JPG",
  صدقة: "adjectives/صدقة.JPG",
  صعب: "adjectives/صعب.JPG",
  ظالم: "adjectives/ظالم.JPG",
  عادل: "adjectives/عادل.JPG",
  عار: "adjectives/عار.JPG",
  عذب: "adjectives/عذب.JPG",
  عزيز: "adjectives/عزيز.JPG",
  عطشان: "adjectives/عطشان.jpg",
  عنيد: "adjectives/عنيد.jpg",
  غشاش: "adjectives/غشاش.jpg",
  غضبان: "adjectives/غضبان.JPG",
  غني: "adjectives/غني.JPG",
  فاهم: "adjectives/فاهم.JPG",
  فرحان: "adjectives/فرحان.JPG",
  فقير: "adjectives/فقير.JPG",
  قبيح: "adjectives/قبيح.jpg",
  قوي: "adjectives/قوي.JPG",
  كذاب: "adjectives/كذاب.JPG",
  كرامة: "adjectives/كرامة.JPG",
  كسلان: "adjectives/كسلان.JPG",
  لامع: "adjectives/لامع.jpg",
  لطيف: "adjectives/لطيف.JPG",
  مؤدب: "adjectives/مؤدب.JPG",
  ماهر: "adjectives/ماهر.jpg",
  مباشر: "adjectives/مباشر.JPG",
  متخاصم: "adjectives/متخاصم.JPG",
  متطوع: "adjectives/متطوع.JPG",
  متعاون: "adjectives/متعاون.jpg",
  متكبر: "adjectives/متكبر.JPG",
  متواضع: "adjectives/متواضع.JPG",
  متوحش: "adjectives/متوحش.JPG",
  مثير: "adjectives/مثير.JPG",
  مجتهد: "adjectives/مجتهد.JPG",
  مجنون: "adjectives/مجنون.JPG",
  محبوب: "adjectives/محبوب.JPG",
  محكم: "adjectives/محكم.JPG",
  مختلس: "adjectives/مختلس.JPG",
  مخلص: "adjectives/مخلص.JPG",
  مدبب: "adjectives/مدبب.JPG",
  مديون: "adjectives/مديون.JPG",
  مرتاح: "adjectives/مرتاح.JPG",
  مرتبك: "adjectives/مرتبك.JPG",
  مزور: "adjectives/مزور.JPG",
  مستنكر: "adjectives/مستنكر.JPG",
  مسكين: "adjectives/مسكين.JPG",
  مشمئز: "adjectives/مشمئز.jpg",
  مفاجاة: "adjectives/مفاجاة.JPG",
  ملاك: "adjectives/ملاك.JPG",
  مناضل: "adjectives/مناضل.JPG",
  موفق: "adjectives/موفق.JPG",
  ناجح: "adjectives/ناجح.jpg",
  ناعم: "adjectives/ناعم.JPG",
  نافع: "adjectives/نافع.jpg",
  نشيط: "adjectives/نشيط.JPG",
  نظيف: "adjectives/نظيف.JPG",
  هيبة: "adjectives/هيبة.JPG",
  وسخ: "adjectives/وسخ.JPG",
};

export default words;